server:
  port: 8080

spring:
  application:
    name: ms-api-gateway
  config:
    import: optional:configserver:http://microservice-config-server:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-tasks-manager
          uri: http://microservice-tasks-manager:8090
          predicates:
            - Path=/api/v1/tasks/**
eureka:
  client:
    register-with-eureka: false